SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mydb`.`Orders` (
  `OrderNumber` INT NOT NULL ,
  `Quantity` INT NOT NULL ,
  `Address` TEXT NOT NULL ,
  `PhoneNumber` VARCHAR(20) DEFAULT NULL ,
  `Payment` DECIMAL(15,2) DEFAULT NULL
  PRIMARY KEY (`OrderNumber`)
)
ENGINE = InnoDB;

USE `mydb` ;

INSERT INTO `Orders` VALUES (1,1,"Delhi","1234567890",100);
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

